defmodule Digsync.Repo.Migrations.AddMvpUserFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :facebook_link, :text
      add :instagram_link, :text
      add :linkedin_link, :text
      add :github_link, :text
      add :gender, :text, default: "male"
      add :age, :bigint
      add :bio, :text
      add :skill_level, :text
    end
  end

  def down do
    alter table(:users) do
      remove :skill_level
      remove :bio
      remove :age
      remove :gender
      remove :github_link
      remove :linkedin_link
      remove :instagram_link
      remove :facebook_link
    end
  end
end