defmodule Digsync.Repo.Migrations.RemoveDeletedAtNonNull do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:friend_requests) do
      modify :deleted_at, :utc_datetime_usec, null: true
    end
  end

  def down do
    alter table(:friend_requests) do
      modify :deleted_at, :utc_datetime_usec, null: false
    end
  end
end