defmodule Digsync.Repo.Migrations.CreatorToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("messages", "messages_pkey")

    alter table(:messages) do
      add :creator_id,
          references(:users,
            column: :id,
            name: "messages_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end

    alter table(:groups) do
      modify :type, :text, default: "social"
    end
  end

  def down do
    drop constraint("messages", "messages_pkey")

    alter table(:groups) do
      modify :type, :text, default: nil
    end

    drop constraint(:messages, "messages_creator_id_fkey")

    alter table(:messages) do
      remove :creator_id
    end
  end
end
