defmodule Digsync.Repo.Migrations.AddFirstLastEmailAndPnToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :first_name, :text
      add :last_name, :text
      add :phone_number, :text
    end
  end

  def down do
    alter table(:users) do
      remove :phone_number
      remove :last_name
      remove :first_name
    end
  end
end
