defmodule Digsync.Repo.Migrations.Locations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:locations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :name, :text, null: false
      add :directions, :text, null: false
      add :locaton, :text
      add :preferred_location, :text
      add :type, :text, default: "grass"
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")

      add :creator_id,
          references(:users,
            column: :id,
            name: "locations_creator_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:locations, "locations_creator_id_fkey")

    drop table(:locations)
  end
end