defmodule Digsync.Repo.Migrations.AddAddressToEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :address, :geometry
    end
  end

  def down do
    alter table(:events) do
      remove :address
    end
  end
end
