defmodule Digsync.Repo.Migrations.SoftDeleteFriendRequest do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:friend_requests) do
      add :deleted_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:friend_requests) do
      remove :deleted_at
    end
  end
end