defmodule Digsync.Repo.Migrations.UpdateAdressFieldsUsingGeoPoint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :address, :text
    end

    alter table(:events) do
      modify :address, :text
      add :geo_point, :geometry
    end
  end

  def down do
    alter table(:events) do
      remove :geo_point
      modify :address, :geometry
    end

    alter table(:users) do
      remove :address
    end
  end
end
