defmodule Digsync.Repo.Migrations.AddFriendships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:users), :type, to: :user_type
  end

  def down do
    rename table(:users), :user_type, to: :type
  end
end