defmodule Digsync.Repo.Migrations.AddCityState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:events) do
      add :city, :text
      add :state, :text
    end
  end

  def down do
    alter table(:events) do
      remove :state
      remove :city
    end
  end
end
