defmodule Digsync.Repo.Migrations.GroupMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:group_messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :message_id,
          references(:messages,
            column: :id,
            name: "group_messages_message_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :group_id,
          references(:groups,
            column: :id,
            name: "group_messages_group_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:group_messages, "group_messages_message_id_fkey")

    drop constraint(:group_messages, "group_messages_group_id_fkey")

    drop table(:group_messages)
  end
end