defmodule Digsync.Repo.Migrations.AddFriendshipRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint("friendships", "friendships_pkey")

    alter table(:friendships) do
      add :first_id,
          references(:users,
            column: :id,
            name: "friendships_first_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :second_id,
          references(:users,
            column: :id,
            name: "friendships_second_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint("friendships", "friendships_pkey")

    drop constraint(:friendships, "friendships_first_id_fkey")

    drop constraint(:friendships, "friendships_second_id_fkey")

    alter table(:friendships) do
      remove :second_id
      remove :first_id
    end
  end
end
