defmodule Digsync.Repo.Migrations.AddGroupAdminRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:groups) do
      add :group_admin_id,
          references(:users,
            column: :id,
            name: "groups_group_admin_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:groups, "groups_group_admin_id_fkey")

    alter table(:groups) do
      remove :group_admin_id
    end
  end
end