defmodule Digsync.Repo.Migrations.AddCreateTypeToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :create_type, :text, default: "password"
    end
  end

  def down do
    alter table(:users) do
      remove :create_type
    end
  end
end